//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BibliotecaEntities : DbContext
    {
        public BibliotecaEntities()
            : base("name=BibliotecaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autor> Autor { get; set; }
        public virtual DbSet<Copia> Copia { get; set; }
        public virtual DbSet<DiaNoHabil> DiaNoHabil { get; set; }
        public virtual DbSet<Llibre> Llibre { get; set; }
        public virtual DbSet<LlistaEspera> LlistaEspera { get; set; }
        public virtual DbSet<Prestec> Prestec { get; set; }
        public virtual DbSet<Soci> Soci { get; set; }
    }
}
