//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BibliotecaEntities2 : DbContext
    {
        public BibliotecaEntities2()
            : base("name=BibliotecaEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autors> Autors { get; set; }
        public virtual DbSet<Copias> Copias { get; set; }
        public virtual DbSet<DiesNoHabils> DiesNoHabils { get; set; }
        public virtual DbSet<Llibre> Llibre { get; set; }
        public virtual DbSet<LlistaEspera> LlistaEspera { get; set; }
        public virtual DbSet<Prestecs> Prestecs { get; set; }
        public virtual DbSet<Sancio> Sancio { get; set; }
        public virtual DbSet<Socis> Socis { get; set; }
    }
}
