//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestecs
    {
        public int Id { get; set; }
        public int IdCopia { get; set; }
        public System.DateTime dataInici { get; set; }
        public System.DateTime dataFinal { get; set; }
        public System.DateTime dataReal { get; set; }
        public int Sancios_Id { get; set; }
    
        public virtual Sancio Sancio { get; set; }
    }
}
