//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestec
    {
        public int Id { get; set; }
        public System.DateTime dataInici { get; set; }
        public System.DateTime dataFinal { get; set; }
        public System.DateTime dataRetorn { get; set; }
        public int CopiaId { get; set; }
        public int SocisId { get; set; }
    
        public virtual Copia Copia { get; set; }
        public virtual Soci Soci { get; set; }
    }
}
