//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Sancio> Sancio { get; set; }
        public virtual DbSet<DiesNoHabils> DiesNoHabils { get; set; }
        public virtual DbSet<LlistaEspera> LlistaEspera { get; set; }
        public virtual DbSet<Llibre> Llibre { get; set; }
        public virtual DbSet<Prestec> Prestecs { get; set; }
        public virtual DbSet<Copia> Copias { get; set; }
        public virtual DbSet<Soci> Socis { get; set; }
        public virtual DbSet<Autor> Autors { get; set; }
    }
}
